import { createContext, useEffect, useState } from "react";
import { toggleTheme } from "../functions/theme";
import { browserStore, getBrowserStore } from "./browserStore";

export const AppDataContext = createContext();

function AppDataContextProvifer(props) {
	const [init, setInit] = useState(false);
	const [userData, setUserData] = useState({
		bible: "kjv",
		compare: "",
		selected: {
			book: "Genesis",
			chapter: 1,
		}
	});
	const [appData] = useState({
		books: [
			{
				book: "Genesis",
				num: 1,
				chapters: [
					{ chapter: 1, verse: 31 },
					{ chapter: 2, verse: 25 },
					{ chapter: 3, verse: 24 },
					{ chapter: 4, verse: 26 },
					{ chapter: 5, verse: 32 },
					{ chapter: 6, verse: 22 },
					{ chapter: 7, verse: 24 },
					{ chapter: 8, verse: 22 },
					{ chapter: 9, verse: 29 },
					{ chapter: 10, verse: 32 },
					{ chapter: 11, verse: 32 },
					{ chapter: 12, verse: 20 },
					{ chapter: 13, verse: 18 },
					{ chapter: 14, verse: 24 },
					{ chapter: 15, verse: 21 },
					{ chapter: 16, verse: 16 },
					{ chapter: 17, verse: 27 },
					{ chapter: 18, verse: 33 },
					{ chapter: 19, verse: 38 },
					{ chapter: 20, verse: 18 },
					{ chapter: 21, verse: 34 },
					{ chapter: 22, verse: 24 },
					{ chapter: 23, verse: 20 },
					{ chapter: 24, verse: 67 },
					{ chapter: 25, verse: 34 },
					{ chapter: 26, verse: 35 },
					{ chapter: 27, verse: 46 },
					{ chapter: 28, verse: 22 },
					{ chapter: 29, verse: 35 },
					{ chapter: 30, verse: 43 },
					{ chapter: 31, verse: 55 },
					{ chapter: 32, verse: 32 },
					{ chapter: 33, verse: 20 },
					{ chapter: 34, verse: 31 },
					{ chapter: 35, verse: 29 },
					{ chapter: 36, verse: 43 },
					{ chapter: 37, verse: 36 },
					{ chapter: 38, verse: 30 },
					{ chapter: 39, verse: 23 },
					{ chapter: 40, verse: 23 },
					{ chapter: 41, verse: 57 },
					{ chapter: 42, verse: 38 },
					{ chapter: 43, verse: 34 },
					{ chapter: 44, verse: 34 },
					{ chapter: 45, verse: 28 },
					{ chapter: 46, verse: 34 },
					{ chapter: 47, verse: 31 },
					{ chapter: 48, verse: 22 },
					{ chapter: 49, verse: 33 },
					{ chapter: 50, verse: 26 },
				],
			},
			{
				book: "Exodus",
				num: 2,
				chapters: [
					{ chapter: 1, verse: 22 },
					{ chapter: 2, verse: 25 },
					{ chapter: 3, verse: 22 },
					{ chapter: 4, verse: 31 },
					{ chapter: 5, verse: 23 },
					{ chapter: 6, verse: 30 },
					{ chapter: 7, verse: 25 },
					{ chapter: 8, verse: 32 },
					{ chapter: 9, verse: 35 },
					{ chapter: 10, verse: 29 },
					{ chapter: 11, verse: 10 },
					{ chapter: 12, verse: 51 },
					{ chapter: 13, verse: 22 },
					{ chapter: 14, verse: 31 },
					{ chapter: 15, verse: 27 },
					{ chapter: 16, verse: 36 },
					{ chapter: 17, verse: 16 },
					{ chapter: 18, verse: 27 },
					{ chapter: 19, verse: 25 },
					{ chapter: 20, verse: 26 },
					{ chapter: 21, verse: 36 },
					{ chapter: 22, verse: 31 },
					{ chapter: 23, verse: 33 },
					{ chapter: 24, verse: 18 },
					{ chapter: 25, verse: 40 },
					{ chapter: 26, verse: 37 },
					{ chapter: 27, verse: 21 },
					{ chapter: 28, verse: 43 },
					{ chapter: 29, verse: 46 },
					{ chapter: 30, verse: 38 },
					{ chapter: 31, verse: 18 },
					{ chapter: 32, verse: 35 },
					{ chapter: 33, verse: 23 },
					{ chapter: 34, verse: 35 },
					{ chapter: 35, verse: 35 },
					{ chapter: 36, verse: 38 },
					{ chapter: 37, verse: 29 },
					{ chapter: 38, verse: 31 },
					{ chapter: 39, verse: 43 },
					{ chapter: 40, verse: 38 },
				],
			},
			{
				book: "Leviticus",
				num: 3,
				chapters: [
					{ chapter: 1, verse: 17 },
					{ chapter: 2, verse: 16 },
					{ chapter: 3, verse: 17 },
					{ chapter: 4, verse: 35 },
					{ chapter: 5, verse: 19 },
					{ chapter: 6, verse: 30 },
					{ chapter: 7, verse: 38 },
					{ chapter: 8, verse: 36 },
					{ chapter: 9, verse: 24 },
					{ chapter: 10, verse: 20 },
					{ chapter: 11, verse: 47 },
					{ chapter: 12, verse: 8 },
					{ chapter: 13, verse: 59 },
					{ chapter: 14, verse: 57 },
					{ chapter: 15, verse: 33 },
					{ chapter: 16, verse: 34 },
					{ chapter: 17, verse: 16 },
					{ chapter: 18, verse: 30 },
					{ chapter: 19, verse: 37 },
					{ chapter: 20, verse: 27 },
					{ chapter: 21, verse: 24 },
					{ chapter: 22, verse: 33 },
					{ chapter: 23, verse: 44 },
					{ chapter: 24, verse: 23 },
					{ chapter: 25, verse: 55 },
					{ chapter: 26, verse: 46 },
					{ chapter: 27, verse: 34 },
				],
			},
			{
				book: "Numbers",
				num: 4,
				chapters: [
					{ chapter: 1, verse: 54 },
					{ chapter: 2, verse: 34 },
					{ chapter: 3, verse: 51 },
					{ chapter: 4, verse: 49 },
					{ chapter: 5, verse: 31 },
					{ chapter: 6, verse: 27 },
					{ chapter: 7, verse: 89 },
					{ chapter: 8, verse: 26 },
					{ chapter: 9, verse: 23 },
					{ chapter: 10, verse: 36 },
					{ chapter: 11, verse: 35 },
					{ chapter: 12, verse: 16 },
					{ chapter: 13, verse: 33 },
					{ chapter: 14, verse: 45 },
					{ chapter: 15, verse: 41 },
					{ chapter: 16, verse: 50 },
					{ chapter: 17, verse: 13 },
					{ chapter: 18, verse: 32 },
					{ chapter: 19, verse: 22 },
					{ chapter: 20, verse: 29 },
					{ chapter: 21, verse: 35 },
					{ chapter: 22, verse: 41 },
					{ chapter: 23, verse: 30 },
					{ chapter: 24, verse: 25 },
					{ chapter: 25, verse: 18 },
					{ chapter: 26, verse: 65 },
					{ chapter: 27, verse: 23 },
					{ chapter: 28, verse: 31 },
					{ chapter: 29, verse: 40 },
					{ chapter: 30, verse: 16 },
					{ chapter: 31, verse: 54 },
					{ chapter: 32, verse: 42 },
					{ chapter: 33, verse: 56 },
					{ chapter: 34, verse: 29 },
					{ chapter: 35, verse: 34 },
					{ chapter: 36, verse: 13 },
				],
			},
			{
				book: "Deuteronomy",
				num: 5,
				chapters: [
					{ chapter: 1, verse: 46 },
					{ chapter: 2, verse: 37 },
					{ chapter: 3, verse: 29 },
					{ chapter: 4, verse: 49 },
					{ chapter: 5, verse: 33 },
					{ chapter: 6, verse: 25 },
					{ chapter: 7, verse: 26 },
					{ chapter: 8, verse: 20 },
					{ chapter: 9, verse: 29 },
					{ chapter: 10, verse: 22 },
					{ chapter: 11, verse: 32 },
					{ chapter: 12, verse: 32 },
					{ chapter: 13, verse: 18 },
					{ chapter: 14, verse: 29 },
					{ chapter: 15, verse: 23 },
					{ chapter: 16, verse: 22 },
					{ chapter: 17, verse: 20 },
					{ chapter: 18, verse: 22 },
					{ chapter: 19, verse: 21 },
					{ chapter: 20, verse: 20 },
					{ chapter: 21, verse: 23 },
					{ chapter: 22, verse: 30 },
					{ chapter: 23, verse: 25 },
					{ chapter: 24, verse: 22 },
					{ chapter: 25, verse: 19 },
					{ chapter: 26, verse: 19 },
					{ chapter: 27, verse: 26 },
					{ chapter: 28, verse: 68 },
					{ chapter: 29, verse: 29 },
					{ chapter: 30, verse: 20 },
					{ chapter: 31, verse: 30 },
					{ chapter: 32, verse: 52 },
					{ chapter: 33, verse: 29 },
					{ chapter: 34, verse: 12 },
				],
			},
			{
				book: "Joshua",
				num: 6,
				chapters: [
					{ chapter: 1, verse: 18 },
					{ chapter: 2, verse: 24 },
					{ chapter: 3, verse: 17 },
					{ chapter: 4, verse: 24 },
					{ chapter: 5, verse: 15 },
					{ chapter: 6, verse: 27 },
					{ chapter: 7, verse: 26 },
					{ chapter: 8, verse: 35 },
					{ chapter: 9, verse: 27 },
					{ chapter: 10, verse: 43 },
					{ chapter: 11, verse: 23 },
					{ chapter: 12, verse: 24 },
					{ chapter: 13, verse: 33 },
					{ chapter: 14, verse: 15 },
					{ chapter: 15, verse: 63 },
					{ chapter: 16, verse: 10 },
					{ chapter: 17, verse: 18 },
					{ chapter: 18, verse: 28 },
					{ chapter: 19, verse: 51 },
					{ chapter: 20, verse: 9 },
					{ chapter: 21, verse: 45 },
					{ chapter: 22, verse: 34 },
					{ chapter: 23, verse: 16 },
					{ chapter: 24, verse: 33 },
				],
			},
			{
				book: "Judges",
				num: 7,
				chapters: [
					{ chapter: 1, verse: 36 },
					{ chapter: 2, verse: 23 },
					{ chapter: 3, verse: 31 },
					{ chapter: 4, verse: 24 },
					{ chapter: 5, verse: 31 },
					{ chapter: 6, verse: 40 },
					{ chapter: 7, verse: 25 },
					{ chapter: 8, verse: 35 },
					{ chapter: 9, verse: 57 },
					{ chapter: 10, verse: 18 },
					{ chapter: 11, verse: 40 },
					{ chapter: 12, verse: 15 },
					{ chapter: 13, verse: 25 },
					{ chapter: 14, verse: 20 },
					{ chapter: 15, verse: 20 },
					{ chapter: 16, verse: 31 },
					{ chapter: 17, verse: 13 },
					{ chapter: 18, verse: 31 },
					{ chapter: 19, verse: 30 },
					{ chapter: 20, verse: 48 },
					{ chapter: 21, verse: 25 },
				],
			},
			{
				book: "Ruth",
				num: 8,
				chapters: [
					{ chapter: 1, verse: 22 },
					{ chapter: 2, verse: 23 },
					{ chapter: 3, verse: 18 },
					{ chapter: 4, verse: 22 },
				],
			},
			{
				book: "1 Samuel",
				num: 9,
				chapters: [
					{ chapter: 1, verse: 28 },
					{ chapter: 2, verse: 36 },
					{ chapter: 3, verse: 21 },
					{ chapter: 4, verse: 22 },
					{ chapter: 5, verse: 12 },
					{ chapter: 6, verse: 21 },
					{ chapter: 7, verse: 17 },
					{ chapter: 8, verse: 22 },
					{ chapter: 9, verse: 27 },
					{ chapter: 10, verse: 27 },
					{ chapter: 11, verse: 15 },
					{ chapter: 12, verse: 25 },
					{ chapter: 13, verse: 23 },
					{ chapter: 14, verse: 52 },
					{ chapter: 15, verse: 35 },
					{ chapter: 16, verse: 23 },
					{ chapter: 17, verse: 58 },
					{ chapter: 18, verse: 30 },
					{ chapter: 19, verse: 24 },
					{ chapter: 20, verse: 42 },
					{ chapter: 21, verse: 15 },
					{ chapter: 22, verse: 23 },
					{ chapter: 23, verse: 29 },
					{ chapter: 24, verse: 22 },
					{ chapter: 25, verse: 44 },
					{ chapter: 26, verse: 25 },
					{ chapter: 27, verse: 12 },
					{ chapter: 28, verse: 25 },
					{ chapter: 29, verse: 11 },
					{ chapter: 30, verse: 31 },
					{ chapter: 31, verse: 13 },
				],
			},
			{
				book: "2 Samuel",
				num: 10,
				chapters: [
					{ chapter: 1, verse: 27 },
					{ chapter: 2, verse: 32 },
					{ chapter: 3, verse: 39 },
					{ chapter: 4, verse: 12 },
					{ chapter: 5, verse: 25 },
					{ chapter: 6, verse: 23 },
					{ chapter: 7, verse: 29 },
					{ chapter: 8, verse: 18 },
					{ chapter: 9, verse: 13 },
					{ chapter: 10, verse: 19 },
					{ chapter: 11, verse: 27 },
					{ chapter: 12, verse: 31 },
					{ chapter: 13, verse: 39 },
					{ chapter: 14, verse: 33 },
					{ chapter: 15, verse: 37 },
					{ chapter: 16, verse: 23 },
					{ chapter: 17, verse: 29 },
					{ chapter: 18, verse: 33 },
					{ chapter: 19, verse: 43 },
					{ chapter: 20, verse: 26 },
					{ chapter: 21, verse: 22 },
					{ chapter: 22, verse: 51 },
					{ chapter: 23, verse: 39 },
					{ chapter: 24, verse: 25 },
				],
			},
			{
				book: "1 Kings",
				num: 11,
				chapters: [
					{ chapter: 1, verse: 53 },
					{ chapter: 2, verse: 46 },
					{ chapter: 3, verse: 28 },
					{ chapter: 4, verse: 34 },
					{ chapter: 5, verse: 18 },
					{ chapter: 6, verse: 38 },
					{ chapter: 7, verse: 51 },
					{ chapter: 8, verse: 66 },
					{ chapter: 9, verse: 28 },
					{ chapter: 10, verse: 29 },
					{ chapter: 11, verse: 43 },
					{ chapter: 12, verse: 33 },
					{ chapter: 13, verse: 34 },
					{ chapter: 14, verse: 31 },
					{ chapter: 15, verse: 34 },
					{ chapter: 16, verse: 34 },
					{ chapter: 17, verse: 24 },
					{ chapter: 18, verse: 46 },
					{ chapter: 19, verse: 21 },
					{ chapter: 20, verse: 43 },
					{ chapter: 21, verse: 29 },
					{ chapter: 22, verse: 53 },
				],
			},
			{
				book: "2 Kings",
				num: 12,
				chapters: [
					{ chapter: 1, verse: 18 },
					{ chapter: 2, verse: 25 },
					{ chapter: 3, verse: 27 },
					{ chapter: 4, verse: 44 },
					{ chapter: 5, verse: 27 },
					{ chapter: 6, verse: 33 },
					{ chapter: 7, verse: 20 },
					{ chapter: 8, verse: 29 },
					{ chapter: 9, verse: 37 },
					{ chapter: 10, verse: 36 },
					{ chapter: 11, verse: 21 },
					{ chapter: 12, verse: 21 },
					{ chapter: 13, verse: 25 },
					{ chapter: 14, verse: 29 },
					{ chapter: 15, verse: 38 },
					{ chapter: 16, verse: 20 },
					{ chapter: 17, verse: 41 },
					{ chapter: 18, verse: 37 },
					{ chapter: 19, verse: 37 },
					{ chapter: 20, verse: 21 },
					{ chapter: 21, verse: 26 },
					{ chapter: 22, verse: 20 },
					{ chapter: 23, verse: 37 },
					{ chapter: 24, verse: 20 },
					{ chapter: 25, verse: 30 },
				],
			},
			{
				book: "1 Chronicles",
				num: 13,
				chapters: [
					{ chapter: 1, verse: 54 },
					{ chapter: 2, verse: 55 },
					{ chapter: 3, verse: 24 },
					{ chapter: 4, verse: 43 },
					{ chapter: 5, verse: 26 },
					{ chapter: 6, verse: 81 },
					{ chapter: 7, verse: 40 },
					{ chapter: 8, verse: 40 },
					{ chapter: 9, verse: 44 },
					{ chapter: 10, verse: 14 },
					{ chapter: 11, verse: 47 },
					{ chapter: 12, verse: 40 },
					{ chapter: 13, verse: 14 },
					{ chapter: 14, verse: 17 },
					{ chapter: 15, verse: 29 },
					{ chapter: 16, verse: 43 },
					{ chapter: 17, verse: 27 },
					{ chapter: 18, verse: 17 },
					{ chapter: 19, verse: 19 },
					{ chapter: 20, verse: 8 },
					{ chapter: 21, verse: 30 },
					{ chapter: 22, verse: 19 },
					{ chapter: 23, verse: 32 },
					{ chapter: 24, verse: 31 },
					{ chapter: 25, verse: 31 },
					{ chapter: 26, verse: 32 },
					{ chapter: 27, verse: 34 },
					{ chapter: 28, verse: 21 },
					{ chapter: 29, verse: 30 },
				],
			},
			{
				book: "2 Chronicles",
				num: 14,
				chapters: [
					{ chapter: 1, verse: 17 },
					{ chapter: 2, verse: 18 },
					{ chapter: 3, verse: 17 },
					{ chapter: 4, verse: 22 },
					{ chapter: 5, verse: 14 },
					{ chapter: 6, verse: 42 },
					{ chapter: 7, verse: 22 },
					{ chapter: 8, verse: 18 },
					{ chapter: 9, verse: 31 },
					{ chapter: 10, verse: 19 },
					{ chapter: 11, verse: 23 },
					{ chapter: 12, verse: 16 },
					{ chapter: 13, verse: 22 },
					{ chapter: 14, verse: 15 },
					{ chapter: 15, verse: 19 },
					{ chapter: 16, verse: 14 },
					{ chapter: 17, verse: 19 },
					{ chapter: 18, verse: 34 },
					{ chapter: 19, verse: 11 },
					{ chapter: 20, verse: 37 },
					{ chapter: 21, verse: 20 },
					{ chapter: 22, verse: 12 },
					{ chapter: 23, verse: 21 },
					{ chapter: 24, verse: 27 },
					{ chapter: 25, verse: 28 },
					{ chapter: 26, verse: 23 },
					{ chapter: 27, verse: 9 },
					{ chapter: 28, verse: 27 },
					{ chapter: 29, verse: 36 },
					{ chapter: 30, verse: 27 },
					{ chapter: 31, verse: 21 },
					{ chapter: 32, verse: 33 },
					{ chapter: 33, verse: 25 },
					{ chapter: 34, verse: 33 },
					{ chapter: 35, verse: 27 },
					{ chapter: 36, verse: 23 },
				],
			},
			{
				book: "Ezra",
				num: 15,
				chapters: [
					{ chapter: 1, verse: 11 },
					{ chapter: 2, verse: 70 },
					{ chapter: 3, verse: 13 },
					{ chapter: 4, verse: 24 },
					{ chapter: 5, verse: 17 },
					{ chapter: 6, verse: 22 },
					{ chapter: 7, verse: 28 },
					{ chapter: 8, verse: 36 },
					{ chapter: 9, verse: 15 },
					{ chapter: 10, verse: 44 },
				],
			},
			{
				book: "Nehemiah",
				num: 16,
				chapters: [
					{ chapter: 1, verse: 11 },
					{ chapter: 2, verse: 20 },
					{ chapter: 3, verse: 32 },
					{ chapter: 4, verse: 23 },
					{ chapter: 5, verse: 19 },
					{ chapter: 6, verse: 19 },
					{ chapter: 7, verse: 73 },
					{ chapter: 8, verse: 18 },
					{ chapter: 9, verse: 38 },
					{ chapter: 10, verse: 39 },
					{ chapter: 11, verse: 36 },
					{ chapter: 12, verse: 47 },
					{ chapter: 13, verse: 31 },
				],
			},
			{
				book: "Esther",
				num: 17,
				chapters: [
					{ chapter: 1, verse: 22 },
					{ chapter: 2, verse: 23 },
					{ chapter: 3, verse: 15 },
					{ chapter: 4, verse: 17 },
					{ chapter: 5, verse: 14 },
					{ chapter: 6, verse: 14 },
					{ chapter: 7, verse: 10 },
					{ chapter: 8, verse: 17 },
					{ chapter: 9, verse: 32 },
					{ chapter: 10, verse: 3 },
				],
			},
			{
				book: "Job",
				num: 18,
				chapters: [
					{ chapter: 1, verse: 22 },
					{ chapter: 2, verse: 13 },
					{ chapter: 3, verse: 26 },
					{ chapter: 4, verse: 21 },
					{ chapter: 5, verse: 27 },
					{ chapter: 6, verse: 30 },
					{ chapter: 7, verse: 21 },
					{ chapter: 8, verse: 22 },
					{ chapter: 9, verse: 35 },
					{ chapter: 10, verse: 22 },
					{ chapter: 11, verse: 20 },
					{ chapter: 12, verse: 25 },
					{ chapter: 13, verse: 28 },
					{ chapter: 14, verse: 22 },
					{ chapter: 15, verse: 35 },
					{ chapter: 16, verse: 22 },
					{ chapter: 17, verse: 16 },
					{ chapter: 18, verse: 21 },
					{ chapter: 19, verse: 29 },
					{ chapter: 20, verse: 29 },
					{ chapter: 21, verse: 34 },
					{ chapter: 22, verse: 30 },
					{ chapter: 23, verse: 17 },
					{ chapter: 24, verse: 25 },
					{ chapter: 25, verse: 6 },
					{ chapter: 26, verse: 14 },
					{ chapter: 27, verse: 23 },
					{ chapter: 28, verse: 28 },
					{ chapter: 29, verse: 25 },
					{ chapter: 30, verse: 31 },
					{ chapter: 31, verse: 40 },
					{ chapter: 32, verse: 22 },
					{ chapter: 33, verse: 33 },
					{ chapter: 34, verse: 37 },
					{ chapter: 35, verse: 16 },
					{ chapter: 36, verse: 33 },
					{ chapter: 37, verse: 24 },
					{ chapter: 38, verse: 41 },
					{ chapter: 39, verse: 30 },
					{ chapter: 40, verse: 24 },
					{ chapter: 41, verse: 34 },
					{ chapter: 42, verse: 17 },
				],
			},
			{
				book: "Psalm",
				num: 19,
				chapters: [
					{ chapter: 1, verse: 6 },
					{ chapter: 2, verse: 12 },
					{ chapter: 3, verse: 8 },
					{ chapter: 4, verse: 8 },
					{ chapter: 5, verse: 12 },
					{ chapter: 6, verse: 10 },
					{ chapter: 7, verse: 17 },
					{ chapter: 8, verse: 9 },
					{ chapter: 9, verse: 20 },
					{ chapter: 10, verse: 18 },
					{ chapter: 11, verse: 7 },
					{ chapter: 12, verse: 8 },
					{ chapter: 13, verse: 6 },
					{ chapter: 14, verse: 7 },
					{ chapter: 15, verse: 5 },
					{ chapter: 16, verse: 11 },
					{ chapter: 17, verse: 15 },
					{ chapter: 18, verse: 50 },
					{ chapter: 19, verse: 14 },
					{ chapter: 20, verse: 9 },
					{ chapter: 21, verse: 13 },
					{ chapter: 22, verse: 31 },
					{ chapter: 23, verse: 6 },
					{ chapter: 24, verse: 10 },
					{ chapter: 25, verse: 22 },
					{ chapter: 26, verse: 12 },
					{ chapter: 27, verse: 14 },
					{ chapter: 28, verse: 9 },
					{ chapter: 29, verse: 11 },
					{ chapter: 30, verse: 12 },
					{ chapter: 31, verse: 24 },
					{ chapter: 32, verse: 11 },
					{ chapter: 33, verse: 22 },
					{ chapter: 34, verse: 22 },
					{ chapter: 35, verse: 28 },
					{ chapter: 36, verse: 12 },
					{ chapter: 37, verse: 40 },
					{ chapter: 38, verse: 22 },
					{ chapter: 39, verse: 13 },
					{ chapter: 40, verse: 17 },
					{ chapter: 41, verse: 13 },
					{ chapter: 42, verse: 11 },
					{ chapter: 43, verse: 5 },
					{ chapter: 44, verse: 26 },
					{ chapter: 45, verse: 17 },
					{ chapter: 46, verse: 11 },
					{ chapter: 47, verse: 9 },
					{ chapter: 48, verse: 14 },
					{ chapter: 49, verse: 20 },
					{ chapter: 50, verse: 23 },
					{ chapter: 51, verse: 19 },
					{ chapter: 52, verse: 9 },
					{ chapter: 53, verse: 6 },
					{ chapter: 54, verse: 7 },
					{ chapter: 55, verse: 23 },
					{ chapter: 56, verse: 13 },
					{ chapter: 57, verse: 11 },
					{ chapter: 58, verse: 11 },
					{ chapter: 59, verse: 17 },
					{ chapter: 60, verse: 12 },
					{ chapter: 61, verse: 8 },
					{ chapter: 62, verse: 12 },
					{ chapter: 63, verse: 11 },
					{ chapter: 64, verse: 10 },
					{ chapter: 65, verse: 13 },
					{ chapter: 66, verse: 20 },
					{ chapter: 67, verse: 7 },
					{ chapter: 68, verse: 35 },
					{ chapter: 69, verse: 36 },
					{ chapter: 70, verse: 5 },
					{ chapter: 71, verse: 24 },
					{ chapter: 72, verse: 20 },
					{ chapter: 73, verse: 28 },
					{ chapter: 74, verse: 23 },
					{ chapter: 75, verse: 10 },
					{ chapter: 76, verse: 12 },
					{ chapter: 77, verse: 20 },
					{ chapter: 78, verse: 72 },
					{ chapter: 79, verse: 13 },
					{ chapter: 80, verse: 19 },
					{ chapter: 81, verse: 16 },
					{ chapter: 82, verse: 8 },
					{ chapter: 83, verse: 18 },
					{ chapter: 84, verse: 12 },
					{ chapter: 85, verse: 13 },
					{ chapter: 86, verse: 17 },
					{ chapter: 87, verse: 7 },
					{ chapter: 88, verse: 18 },
					{ chapter: 89, verse: 52 },
					{ chapter: 90, verse: 17 },
					{ chapter: 91, verse: 16 },
					{ chapter: 92, verse: 15 },
					{ chapter: 93, verse: 5 },
					{ chapter: 94, verse: 23 },
					{ chapter: 95, verse: 11 },
					{ chapter: 96, verse: 13 },
					{ chapter: 97, verse: 12 },
					{ chapter: 98, verse: 9 },
					{ chapter: 99, verse: 9 },
					{ chapter: 100, verse: 5 },
					{ chapter: 101, verse: 8 },
					{ chapter: 102, verse: 28 },
					{ chapter: 103, verse: 22 },
					{ chapter: 104, verse: 35 },
					{ chapter: 105, verse: 45 },
					{ chapter: 106, verse: 48 },
					{ chapter: 107, verse: 43 },
					{ chapter: 108, verse: 13 },
					{ chapter: 109, verse: 31 },
					{ chapter: 110, verse: 7 },
					{ chapter: 111, verse: 10 },
					{ chapter: 112, verse: 10 },
					{ chapter: 113, verse: 9 },
					{ chapter: 114, verse: 8 },
					{ chapter: 115, verse: 18 },
					{ chapter: 116, verse: 19 },
					{ chapter: 117, verse: 2 },
					{ chapter: 118, verse: 29 },
					{ chapter: 119, verse: 176 },
					{ chapter: 120, verse: 7 },
					{ chapter: 121, verse: 8 },
					{ chapter: 122, verse: 9 },
					{ chapter: 123, verse: 4 },
					{ chapter: 124, verse: 8 },
					{ chapter: 125, verse: 5 },
					{ chapter: 126, verse: 6 },
					{ chapter: 127, verse: 5 },
					{ chapter: 128, verse: 6 },
					{ chapter: 129, verse: 8 },
					{ chapter: 130, verse: 8 },
					{ chapter: 131, verse: 3 },
					{ chapter: 132, verse: 18 },
					{ chapter: 133, verse: 3 },
					{ chapter: 134, verse: 3 },
					{ chapter: 135, verse: 21 },
					{ chapter: 136, verse: 26 },
					{ chapter: 137, verse: 9 },
					{ chapter: 138, verse: 8 },
					{ chapter: 139, verse: 24 },
					{ chapter: 140, verse: 13 },
					{ chapter: 141, verse: 10 },
					{ chapter: 142, verse: 7 },
					{ chapter: 143, verse: 12 },
					{ chapter: 144, verse: 15 },
					{ chapter: 145, verse: 21 },
					{ chapter: 146, verse: 10 },
					{ chapter: 147, verse: 20 },
					{ chapter: 148, verse: 14 },
					{ chapter: 149, verse: 9 },
					{ chapter: 150, verse: 6 },
				],
			},
			{
				book: "Proverbs",
				num: 20,
				chapters: [
					{ chapter: 1, verse: 33 },
					{ chapter: 2, verse: 22 },
					{ chapter: 3, verse: 35 },
					{ chapter: 4, verse: 27 },
					{ chapter: 5, verse: 23 },
					{ chapter: 6, verse: 35 },
					{ chapter: 7, verse: 27 },
					{ chapter: 8, verse: 36 },
					{ chapter: 9, verse: 18 },
					{ chapter: 10, verse: 32 },
					{ chapter: 11, verse: 31 },
					{ chapter: 12, verse: 28 },
					{ chapter: 13, verse: 25 },
					{ chapter: 14, verse: 35 },
					{ chapter: 15, verse: 33 },
					{ chapter: 16, verse: 33 },
					{ chapter: 17, verse: 28 },
					{ chapter: 18, verse: 24 },
					{ chapter: 19, verse: 29 },
					{ chapter: 20, verse: 30 },
					{ chapter: 21, verse: 31 },
					{ chapter: 22, verse: 29 },
					{ chapter: 23, verse: 35 },
					{ chapter: 24, verse: 34 },
					{ chapter: 25, verse: 28 },
					{ chapter: 26, verse: 28 },
					{ chapter: 27, verse: 27 },
					{ chapter: 28, verse: 28 },
					{ chapter: 29, verse: 27 },
					{ chapter: 30, verse: 33 },
					{ chapter: 31, verse: 31 },
				],
			},
			{
				book: "Ecclesiastes",
				num: 21,
				chapters: [
					{ chapter: 1, verse: 18 },
					{ chapter: 2, verse: 26 },
					{ chapter: 3, verse: 22 },
					{ chapter: 4, verse: 16 },
					{ chapter: 5, verse: 20 },
					{ chapter: 6, verse: 12 },
					{ chapter: 7, verse: 29 },
					{ chapter: 8, verse: 17 },
					{ chapter: 9, verse: 18 },
					{ chapter: 10, verse: 20 },
					{ chapter: 11, verse: 10 },
					{ chapter: 12, verse: 14 },
				],
			},
			{
				book: "Song of Solomon",
				num: 22,
				chapters: [
					{ chapter: 1, verse: 17 },
					{ chapter: 2, verse: 17 },
					{ chapter: 3, verse: 11 },
					{ chapter: 4, verse: 16 },
					{ chapter: 5, verse: 16 },
					{ chapter: 6, verse: 13 },
					{ chapter: 7, verse: 13 },
					{ chapter: 8, verse: 14 },
				],
			},
			{
				book: "Isaiah",
				num: 23,
				chapters: [
					{ chapter: 1, verse: 31 },
					{ chapter: 2, verse: 22 },
					{ chapter: 3, verse: 26 },
					{ chapter: 4, verse: 6 },
					{ chapter: 5, verse: 30 },
					{ chapter: 6, verse: 13 },
					{ chapter: 7, verse: 25 },
					{ chapter: 8, verse: 22 },
					{ chapter: 9, verse: 21 },
					{ chapter: 10, verse: 34 },
					{ chapter: 11, verse: 16 },
					{ chapter: 12, verse: 6 },
					{ chapter: 13, verse: 22 },
					{ chapter: 14, verse: 32 },
					{ chapter: 15, verse: 9 },
					{ chapter: 16, verse: 14 },
					{ chapter: 17, verse: 14 },
					{ chapter: 18, verse: 7 },
					{ chapter: 19, verse: 25 },
					{ chapter: 20, verse: 6 },
					{ chapter: 21, verse: 17 },
					{ chapter: 22, verse: 25 },
					{ chapter: 23, verse: 18 },
					{ chapter: 24, verse: 23 },
					{ chapter: 25, verse: 12 },
					{ chapter: 26, verse: 21 },
					{ chapter: 27, verse: 13 },
					{ chapter: 28, verse: 29 },
					{ chapter: 29, verse: 24 },
					{ chapter: 30, verse: 33 },
					{ chapter: 31, verse: 9 },
					{ chapter: 32, verse: 20 },
					{ chapter: 33, verse: 24 },
					{ chapter: 34, verse: 17 },
					{ chapter: 35, verse: 10 },
					{ chapter: 36, verse: 22 },
					{ chapter: 37, verse: 38 },
					{ chapter: 38, verse: 22 },
					{ chapter: 39, verse: 8 },
					{ chapter: 40, verse: 31 },
					{ chapter: 41, verse: 29 },
					{ chapter: 42, verse: 25 },
					{ chapter: 43, verse: 28 },
					{ chapter: 44, verse: 28 },
					{ chapter: 45, verse: 25 },
					{ chapter: 46, verse: 13 },
					{ chapter: 47, verse: 15 },
					{ chapter: 48, verse: 22 },
					{ chapter: 49, verse: 26 },
					{ chapter: 50, verse: 11 },
					{ chapter: 51, verse: 23 },
					{ chapter: 52, verse: 15 },
					{ chapter: 53, verse: 12 },
					{ chapter: 54, verse: 17 },
					{ chapter: 55, verse: 13 },
					{ chapter: 56, verse: 12 },
					{ chapter: 57, verse: 21 },
					{ chapter: 58, verse: 14 },
					{ chapter: 59, verse: 21 },
					{ chapter: 60, verse: 22 },
					{ chapter: 61, verse: 11 },
					{ chapter: 62, verse: 12 },
					{ chapter: 63, verse: 19 },
					{ chapter: 64, verse: 12 },
					{ chapter: 65, verse: 25 },
					{ chapter: 66, verse: 24 },
				],
			},
			{
				book: "Jeremiah",
				num: 24,
				chapters: [
					{ chapter: 1, verse: 19 },
					{ chapter: 2, verse: 37 },
					{ chapter: 3, verse: 25 },
					{ chapter: 4, verse: 31 },
					{ chapter: 5, verse: 31 },
					{ chapter: 6, verse: 30 },
					{ chapter: 7, verse: 34 },
					{ chapter: 8, verse: 22 },
					{ chapter: 9, verse: 26 },
					{ chapter: 10, verse: 25 },
					{ chapter: 11, verse: 23 },
					{ chapter: 12, verse: 17 },
					{ chapter: 13, verse: 27 },
					{ chapter: 14, verse: 22 },
					{ chapter: 15, verse: 21 },
					{ chapter: 16, verse: 21 },
					{ chapter: 17, verse: 27 },
					{ chapter: 18, verse: 23 },
					{ chapter: 19, verse: 15 },
					{ chapter: 20, verse: 18 },
					{ chapter: 21, verse: 14 },
					{ chapter: 22, verse: 30 },
					{ chapter: 23, verse: 40 },
					{ chapter: 24, verse: 10 },
					{ chapter: 25, verse: 38 },
					{ chapter: 26, verse: 24 },
					{ chapter: 27, verse: 22 },
					{ chapter: 28, verse: 17 },
					{ chapter: 29, verse: 32 },
					{ chapter: 30, verse: 24 },
					{ chapter: 31, verse: 40 },
					{ chapter: 32, verse: 44 },
					{ chapter: 33, verse: 26 },
					{ chapter: 34, verse: 22 },
					{ chapter: 35, verse: 19 },
					{ chapter: 36, verse: 32 },
					{ chapter: 37, verse: 21 },
					{ chapter: 38, verse: 28 },
					{ chapter: 39, verse: 18 },
					{ chapter: 40, verse: 16 },
					{ chapter: 41, verse: 18 },
					{ chapter: 42, verse: 22 },
					{ chapter: 43, verse: 13 },
					{ chapter: 44, verse: 30 },
					{ chapter: 45, verse: 5 },
					{ chapter: 46, verse: 28 },
					{ chapter: 47, verse: 7 },
					{ chapter: 48, verse: 47 },
					{ chapter: 49, verse: 39 },
					{ chapter: 50, verse: 46 },
					{ chapter: 51, verse: 64 },
					{ chapter: 52, verse: 34 },
				],
			},
			{
				book: "Lamentations",
				num: 25,
				chapters: [
					{ chapter: 1, verse: 22 },
					{ chapter: 2, verse: 22 },
					{ chapter: 3, verse: 66 },
					{ chapter: 4, verse: 22 },
					{ chapter: 5, verse: 22 },
				],
			},
			{
				book: "Ezekiel",
				num: 26,
				chapters: [
					{ chapter: 1, verse: 28 },
					{ chapter: 2, verse: 10 },
					{ chapter: 3, verse: 27 },
					{ chapter: 4, verse: 17 },
					{ chapter: 5, verse: 17 },
					{ chapter: 6, verse: 14 },
					{ chapter: 7, verse: 27 },
					{ chapter: 8, verse: 18 },
					{ chapter: 9, verse: 11 },
					{ chapter: 10, verse: 22 },
					{ chapter: 11, verse: 25 },
					{ chapter: 12, verse: 28 },
					{ chapter: 13, verse: 23 },
					{ chapter: 14, verse: 23 },
					{ chapter: 15, verse: 8 },
					{ chapter: 16, verse: 63 },
					{ chapter: 17, verse: 24 },
					{ chapter: 18, verse: 32 },
					{ chapter: 19, verse: 14 },
					{ chapter: 20, verse: 49 },
					{ chapter: 21, verse: 32 },
					{ chapter: 22, verse: 31 },
					{ chapter: 23, verse: 49 },
					{ chapter: 24, verse: 27 },
					{ chapter: 25, verse: 17 },
					{ chapter: 26, verse: 21 },
					{ chapter: 27, verse: 36 },
					{ chapter: 28, verse: 26 },
					{ chapter: 29, verse: 21 },
					{ chapter: 30, verse: 26 },
					{ chapter: 31, verse: 18 },
					{ chapter: 32, verse: 32 },
					{ chapter: 33, verse: 33 },
					{ chapter: 34, verse: 31 },
					{ chapter: 35, verse: 15 },
					{ chapter: 36, verse: 38 },
					{ chapter: 37, verse: 28 },
					{ chapter: 38, verse: 23 },
					{ chapter: 39, verse: 29 },
					{ chapter: 40, verse: 49 },
					{ chapter: 41, verse: 26 },
					{ chapter: 42, verse: 20 },
					{ chapter: 43, verse: 27 },
					{ chapter: 44, verse: 31 },
					{ chapter: 45, verse: 25 },
					{ chapter: 46, verse: 24 },
					{ chapter: 47, verse: 23 },
					{ chapter: 48, verse: 35 },
				],
			},
			{
				book: "Daniel",
				num: 27,
				chapters: [
					{ chapter: 1, verse: 21 },
					{ chapter: 2, verse: 49 },
					{ chapter: 3, verse: 30 },
					{ chapter: 4, verse: 37 },
					{ chapter: 5, verse: 31 },
					{ chapter: 6, verse: 28 },
					{ chapter: 7, verse: 28 },
					{ chapter: 8, verse: 27 },
					{ chapter: 9, verse: 27 },
					{ chapter: 10, verse: 21 },
					{ chapter: 11, verse: 45 },
					{ chapter: 12, verse: 13 },
				],
			},
			{
				book: "Hosea",
				num: 28,
				chapters: [
					{ chapter: 1, verse: 11 },
					{ chapter: 2, verse: 23 },
					{ chapter: 3, verse: 5 },
					{ chapter: 4, verse: 19 },
					{ chapter: 5, verse: 15 },
					{ chapter: 6, verse: 11 },
					{ chapter: 7, verse: 16 },
					{ chapter: 8, verse: 14 },
					{ chapter: 9, verse: 17 },
					{ chapter: 10, verse: 15 },
					{ chapter: 11, verse: 12 },
					{ chapter: 12, verse: 14 },
					{ chapter: 13, verse: 16 },
					{ chapter: 14, verse: 9 },
				],
			},
			{
				book: "Joel",
				num: 29,
				chapters: [
					{ chapter: 1, verse: 20 },
					{ chapter: 2, verse: 32 },
					{ chapter: 3, verse: 21 },
				],
			},
			{
				book: "Amos",
				num: 30,
				chapters: [
					{ chapter: 1, verse: 15 },
					{ chapter: 2, verse: 16 },
					{ chapter: 3, verse: 15 },
					{ chapter: 4, verse: 13 },
					{ chapter: 5, verse: 27 },
					{ chapter: 6, verse: 14 },
					{ chapter: 7, verse: 17 },
					{ chapter: 8, verse: 14 },
					{ chapter: 9, verse: 15 },
				],
			},
			{ book: "Obadiah", num: 31, chapters: [{ chapter: 1, verse: 21 }] },
			{
				book: "Jonah",
				num: 32,
				chapters: [
					{ chapter: 1, verse: 17 },
					{ chapter: 2, verse: 10 },
					{ chapter: 3, verse: 10 },
					{ chapter: 4, verse: 11 },
				],
			},
			{
				book: "Micah",
				num: 33,
				chapters: [
					{ chapter: 1, verse: 16 },
					{ chapter: 2, verse: 13 },
					{ chapter: 3, verse: 12 },
					{ chapter: 4, verse: 13 },
					{ chapter: 5, verse: 15 },
					{ chapter: 6, verse: 16 },
					{ chapter: 7, verse: 20 },
				],
			},
			{
				book: "Nahum",
				num: 34,
				chapters: [
					{ chapter: 1, verse: 15 },
					{ chapter: 2, verse: 13 },
					{ chapter: 3, verse: 19 },
				],
			},
			{
				book: "Habakkuk",
				num: 35,
				chapters: [
					{ chapter: 1, verse: 17 },
					{ chapter: 2, verse: 20 },
					{ chapter: 3, verse: 19 },
				],
			},
			{
				book: "Zephaniah",
				num: 36,
				chapters: [
					{ chapter: 1, verse: 18 },
					{ chapter: 2, verse: 15 },
					{ chapter: 3, verse: 20 },
				],
			},
			{
				book: "Haggai",
				num: 37,
				chapters: [
					{ chapter: 1, verse: 15 },
					{ chapter: 2, verse: 23 },
				],
			},
			{
				book: "Zechariah",
				num: 38,
				chapters: [
					{ chapter: 1, verse: 21 },
					{ chapter: 2, verse: 13 },
					{ chapter: 3, verse: 10 },
					{ chapter: 4, verse: 14 },
					{ chapter: 5, verse: 11 },
					{ chapter: 6, verse: 15 },
					{ chapter: 7, verse: 14 },
					{ chapter: 8, verse: 23 },
					{ chapter: 9, verse: 17 },
					{ chapter: 10, verse: 12 },
					{ chapter: 11, verse: 17 },
					{ chapter: 12, verse: 14 },
					{ chapter: 13, verse: 9 },
					{ chapter: 14, verse: 21 },
				],
			},
			{
				book: "Malachi",
				num: 39,
				chapters: [
					{ chapter: 1, verse: 14 },
					{ chapter: 2, verse: 17 },
					{ chapter: 3, verse: 18 },
					{ chapter: 4, verse: 6 },
				],
			},
			{
				book: "Matthew",
				num: 40,
				chapters: [
					{ chapter: 1, verse: 25 },
					{ chapter: 2, verse: 23 },
					{ chapter: 3, verse: 17 },
					{ chapter: 4, verse: 25 },
					{ chapter: 5, verse: 48 },
					{ chapter: 6, verse: 34 },
					{ chapter: 7, verse: 29 },
					{ chapter: 8, verse: 34 },
					{ chapter: 9, verse: 38 },
					{ chapter: 10, verse: 42 },
					{ chapter: 11, verse: 30 },
					{ chapter: 12, verse: 50 },
					{ chapter: 13, verse: 58 },
					{ chapter: 14, verse: 36 },
					{ chapter: 15, verse: 39 },
					{ chapter: 16, verse: 28 },
					{ chapter: 17, verse: 27 },
					{ chapter: 18, verse: 35 },
					{ chapter: 19, verse: 30 },
					{ chapter: 20, verse: 34 },
					{ chapter: 21, verse: 46 },
					{ chapter: 22, verse: 46 },
					{ chapter: 23, verse: 39 },
					{ chapter: 24, verse: 51 },
					{ chapter: 25, verse: 46 },
					{ chapter: 26, verse: 75 },
					{ chapter: 27, verse: 66 },
					{ chapter: 28, verse: 20 },
				],
			},
			{
				book: "Mark",
				num: 41,
				chapters: [
					{ chapter: 1, verse: 45 },
					{ chapter: 2, verse: 28 },
					{ chapter: 3, verse: 35 },
					{ chapter: 4, verse: 41 },
					{ chapter: 5, verse: 43 },
					{ chapter: 6, verse: 56 },
					{ chapter: 7, verse: 37 },
					{ chapter: 8, verse: 38 },
					{ chapter: 9, verse: 50 },
					{ chapter: 10, verse: 52 },
					{ chapter: 11, verse: 33 },
					{ chapter: 12, verse: 44 },
					{ chapter: 13, verse: 37 },
					{ chapter: 14, verse: 72 },
					{ chapter: 15, verse: 47 },
					{ chapter: 16, verse: 20 },
				],
			},
			{
				book: "Luke",
				num: 42,
				chapters: [
					{ chapter: 1, verse: 80 },
					{ chapter: 2, verse: 52 },
					{ chapter: 3, verse: 38 },
					{ chapter: 4, verse: 44 },
					{ chapter: 5, verse: 39 },
					{ chapter: 6, verse: 49 },
					{ chapter: 7, verse: 50 },
					{ chapter: 8, verse: 56 },
					{ chapter: 9, verse: 62 },
					{ chapter: 10, verse: 42 },
					{ chapter: 11, verse: 54 },
					{ chapter: 12, verse: 59 },
					{ chapter: 13, verse: 35 },
					{ chapter: 14, verse: 35 },
					{ chapter: 15, verse: 32 },
					{ chapter: 16, verse: 31 },
					{ chapter: 17, verse: 37 },
					{ chapter: 18, verse: 43 },
					{ chapter: 19, verse: 48 },
					{ chapter: 20, verse: 47 },
					{ chapter: 21, verse: 38 },
					{ chapter: 22, verse: 71 },
					{ chapter: 23, verse: 56 },
					{ chapter: 24, verse: 53 },
				],
			},
			{
				book: "John",
				num: 43,
				chapters: [
					{ chapter: 1, verse: 51 },
					{ chapter: 2, verse: 25 },
					{ chapter: 3, verse: 36 },
					{ chapter: 4, verse: 54 },
					{ chapter: 5, verse: 47 },
					{ chapter: 6, verse: 71 },
					{ chapter: 7, verse: 53 },
					{ chapter: 8, verse: 59 },
					{ chapter: 9, verse: 41 },
					{ chapter: 10, verse: 42 },
					{ chapter: 11, verse: 57 },
					{ chapter: 12, verse: 50 },
					{ chapter: 13, verse: 38 },
					{ chapter: 14, verse: 31 },
					{ chapter: 15, verse: 27 },
					{ chapter: 16, verse: 33 },
					{ chapter: 17, verse: 26 },
					{ chapter: 18, verse: 40 },
					{ chapter: 19, verse: 42 },
					{ chapter: 20, verse: 31 },
					{ chapter: 21, verse: 25 },
				],
			},
			{
				book: "Acts",
				num: 44,
				chapters: [
					{ chapter: 1, verse: 26 },
					{ chapter: 2, verse: 47 },
					{ chapter: 3, verse: 26 },
					{ chapter: 4, verse: 37 },
					{ chapter: 5, verse: 42 },
					{ chapter: 6, verse: 15 },
					{ chapter: 7, verse: 60 },
					{ chapter: 8, verse: 40 },
					{ chapter: 9, verse: 43 },
					{ chapter: 10, verse: 48 },
					{ chapter: 11, verse: 30 },
					{ chapter: 12, verse: 25 },
					{ chapter: 13, verse: 52 },
					{ chapter: 14, verse: 28 },
					{ chapter: 15, verse: 41 },
					{ chapter: 16, verse: 40 },
					{ chapter: 17, verse: 34 },
					{ chapter: 18, verse: 28 },
					{ chapter: 19, verse: 41 },
					{ chapter: 20, verse: 38 },
					{ chapter: 21, verse: 40 },
					{ chapter: 22, verse: 30 },
					{ chapter: 23, verse: 35 },
					{ chapter: 24, verse: 27 },
					{ chapter: 25, verse: 27 },
					{ chapter: 26, verse: 32 },
					{ chapter: 27, verse: 44 },
					{ chapter: 28, verse: 31 },
				],
			},
			{
				book: "Romans",
				num: 45,
				chapters: [
					{ chapter: 1, verse: 32 },
					{ chapter: 2, verse: 29 },
					{ chapter: 3, verse: 31 },
					{ chapter: 4, verse: 25 },
					{ chapter: 5, verse: 21 },
					{ chapter: 6, verse: 23 },
					{ chapter: 7, verse: 25 },
					{ chapter: 8, verse: 39 },
					{ chapter: 9, verse: 33 },
					{ chapter: 10, verse: 21 },
					{ chapter: 11, verse: 36 },
					{ chapter: 12, verse: 21 },
					{ chapter: 13, verse: 14 },
					{ chapter: 14, verse: 23 },
					{ chapter: 15, verse: 33 },
					{ chapter: 16, verse: 27 },
				],
			},
			{
				book: "1 Corinthians",
				num: 46,
				chapters: [
					{ chapter: 1, verse: 31 },
					{ chapter: 2, verse: 16 },
					{ chapter: 3, verse: 23 },
					{ chapter: 4, verse: 21 },
					{ chapter: 5, verse: 13 },
					{ chapter: 6, verse: 20 },
					{ chapter: 7, verse: 40 },
					{ chapter: 8, verse: 13 },
					{ chapter: 9, verse: 27 },
					{ chapter: 10, verse: 33 },
					{ chapter: 11, verse: 34 },
					{ chapter: 12, verse: 31 },
					{ chapter: 13, verse: 13 },
					{ chapter: 14, verse: 40 },
					{ chapter: 15, verse: 58 },
					{ chapter: 16, verse: 24 },
				],
			},
			{
				book: "2 Corinthians",
				num: 47,
				chapters: [
					{ chapter: 1, verse: 24 },
					{ chapter: 2, verse: 17 },
					{ chapter: 3, verse: 18 },
					{ chapter: 4, verse: 18 },
					{ chapter: 5, verse: 21 },
					{ chapter: 6, verse: 18 },
					{ chapter: 7, verse: 16 },
					{ chapter: 8, verse: 24 },
					{ chapter: 9, verse: 15 },
					{ chapter: 10, verse: 18 },
					{ chapter: 11, verse: 33 },
					{ chapter: 12, verse: 21 },
					{ chapter: 13, verse: 14 },
				],
			},
			{
				book: "Galatians",
				num: 48,
				chapters: [
					{ chapter: 1, verse: 24 },
					{ chapter: 2, verse: 21 },
					{ chapter: 3, verse: 29 },
					{ chapter: 4, verse: 31 },
					{ chapter: 5, verse: 26 },
					{ chapter: 6, verse: 18 },
				],
			},
			{
				book: "Ephesians",
				num: 49,
				chapters: [
					{ chapter: 1, verse: 23 },
					{ chapter: 2, verse: 22 },
					{ chapter: 3, verse: 21 },
					{ chapter: 4, verse: 32 },
					{ chapter: 5, verse: 33 },
					{ chapter: 6, verse: 24 },
				],
			},
			{
				book: "Philippians",
				num: 50,
				chapters: [
					{ chapter: 1, verse: 30 },
					{ chapter: 2, verse: 30 },
					{ chapter: 3, verse: 21 },
					{ chapter: 4, verse: 23 },
				],
			},
			{
				book: "Colossians",
				num: 51,
				chapters: [
					{ chapter: 1, verse: 29 },
					{ chapter: 2, verse: 23 },
					{ chapter: 3, verse: 25 },
					{ chapter: 4, verse: 18 },
				],
			},
			{
				book: "1 Thessalonians",
				num: 52,
				chapters: [
					{ chapter: 1, verse: 10 },
					{ chapter: 2, verse: 20 },
					{ chapter: 3, verse: 13 },
					{ chapter: 4, verse: 18 },
					{ chapter: 5, verse: 28 },
				],
			},
			{
				book: "2 Thessalonians",
				num: 53,
				chapters: [
					{ chapter: 1, verse: 12 },
					{ chapter: 2, verse: 17 },
					{ chapter: 3, verse: 18 },
				],
			},
			{
				book: "1 Timothy",
				num: 54,
				chapters: [
					{ chapter: 1, verse: 20 },
					{ chapter: 2, verse: 15 },
					{ chapter: 3, verse: 16 },
					{ chapter: 4, verse: 16 },
					{ chapter: 5, verse: 25 },
					{ chapter: 6, verse: 21 },
				],
			},
			{
				book: "2 Timothy",
				num: 55,
				chapters: [
					{ chapter: 1, verse: 18 },
					{ chapter: 2, verse: 26 },
					{ chapter: 3, verse: 17 },
					{ chapter: 4, verse: 22 },
				],
			},
			{
				book: "Titus",
				num: 56,
				chapters: [
					{ chapter: 1, verse: 16 },
					{ chapter: 2, verse: 15 },
					{ chapter: 3, verse: 15 },
				],
			},
			{
				book: "Philemon",
				num: 57,
				chapters: [{ chapter: 1, verse: 25 }],
			},
			{
				book: "Hebrews",
				num: 58,
				chapters: [
					{ chapter: 1, verse: 14 },
					{ chapter: 2, verse: 18 },
					{ chapter: 3, verse: 19 },
					{ chapter: 4, verse: 16 },
					{ chapter: 5, verse: 14 },
					{ chapter: 6, verse: 20 },
					{ chapter: 7, verse: 28 },
					{ chapter: 8, verse: 13 },
					{ chapter: 9, verse: 28 },
					{ chapter: 10, verse: 39 },
					{ chapter: 11, verse: 40 },
					{ chapter: 12, verse: 29 },
					{ chapter: 13, verse: 25 },
				],
			},
			{
				book: "James",
				num: 59,
				chapters: [
					{ chapter: 1, verse: 27 },
					{ chapter: 2, verse: 26 },
					{ chapter: 3, verse: 18 },
					{ chapter: 4, verse: 17 },
					{ chapter: 5, verse: 20 },
				],
			},
			{
				book: "1 Peter",
				num: 60,
				chapters: [
					{ chapter: 1, verse: 25 },
					{ chapter: 2, verse: 25 },
					{ chapter: 3, verse: 22 },
					{ chapter: 4, verse: 19 },
					{ chapter: 5, verse: 14 },
				],
			},
			{
				book: "2 Peter",
				num: 61,
				chapters: [
					{ chapter: 1, verse: 21 },
					{ chapter: 2, verse: 22 },
					{ chapter: 3, verse: 18 },
				],
			},
			{
				book: "1 John",
				num: 62,
				chapters: [
					{ chapter: 1, verse: 10 },
					{ chapter: 2, verse: 29 },
					{ chapter: 3, verse: 24 },
					{ chapter: 4, verse: 21 },
					{ chapter: 5, verse: 21 },
				],
			},
			{ book: "2 John", num: 63, chapters: [{ chapter: 1, verse: 13 }] },
			{ book: "3 John", num: 64, chapters: [{ chapter: 1, verse: 15 }] },
			{ book: "Jude", num: 65, chapters: [{ chapter: 1, verse: 25 }] },
			{
				book: "Revelation",
				num: 66,
				chapters: [
					{ chapter: 1, verse: 20 },
					{ chapter: 2, verse: 29 },
					{ chapter: 3, verse: 22 },
					{ chapter: 4, verse: 11 },
					{ chapter: 5, verse: 14 },
					{ chapter: 6, verse: 17 },
					{ chapter: 7, verse: 17 },
					{ chapter: 8, verse: 13 },
					{ chapter: 9, verse: 21 },
					{ chapter: 10, verse: 11 },
					{ chapter: 11, verse: 19 },
					{ chapter: 12, verse: 17 },
					{ chapter: 13, verse: 18 },
					{ chapter: 14, verse: 20 },
					{ chapter: 15, verse: 8 },
					{ chapter: 16, verse: 21 },
					{ chapter: 17, verse: 18 },
					{ chapter: 18, verse: 24 },
					{ chapter: 19, verse: 21 },
					{ chapter: 20, verse: 15 },
					{ chapter: 21, verse: 27 },
					{ chapter: 22, verse: 21 },
				],
			},
		],
		bibleList: [
			{
				link: "asv",
				language: "english",
				name: "American Standard Version",
				wiki: "https://en.wikipedia.org/wiki/American_Standard_Version",
				about: 'The Revised Version, Standard American Edition of the Bible, more commonly known as the American Standard Version (ASV), is a Bible translation into English that was completed in 1901, with the publication of the revision of the Old Testament; the revised New Testament had been released in 1900. It was originally best known by its full name, but soon came to have other names, such as the American Revised Version, the American Standard Revision, the American Standard Revised Bible, and the American Standard Edition. By the time its copyright was renewed in 1929, it had come to be known by its present name, the American Standard Version. Because of its prominence in seminaries, it was sometimes simply called the "Standard Bible" in the United States.',
			},
			{
				link: "bbe",
				language: "english",
				name: "Bible in Basic English",
				wiki: "https://en.wikipedia.org/wiki/Bible_in_Basic_English",
				about: "The Bible In Basic English (also known as BBE) is a translation of the Bible into Basic English. The BBE was translated by Professor S. H. Hooke using the standard 850 Basic English words. 100 words that were helpful to understand poetry were added along with 50 'Bible' words for a total of 1,000 words. This version is effective in communicating the Bible to those with limited education or where English is a second language. The New Testament was released in 1941 and the Old Testament was released in 1949",
			},
			{
				link: "kjv",
				language: "english",
				name: "King James Version",
				wiki: "https://en.wikipedia.org/wiki/King_James_Version",
				about: 'The King James Version (KJV), also known as the King James Bible (KJB) or simply the Authorized Version (AV), is an English translation of the Christian Bible for the Church of England, begun in 1604 and completed as well as published in 1611 under the sponsorship of James VI and I.[a][b] The books of the King James Version include the 39 books of the Old Testament, an intertestamental section containing 14 books of the Apocrypha, and the 27 books of the New Testament. The translation is noted for its "majesty of style", and has been described as one of the most important books in English culture[2] and a driving force in the shaping of the English-speaking world.',
			},
			{
				link: "web",
				language: "english",
				name: "World English Bible",
				wiki: "https://en.wikipedia.org/wiki/World_English_Bible",
				about: "The World English Bible (also known as the WEB) is a free updated revision of the American Standard Version (1901). It is one of the few public domain, present-day English translations of the entire Bible, and it is freely distributed to the public using electronic formats. The Bible was created by volunteers using the ASV as the base text as part of the ebible.org project through Rainbow Missions, Inc., a Colorado nonprofit corporation.",
			},
			{
				link: "ylt",
				language: "english",
				name: "Young's Literal Translation",
				wiki: "https://en.wikipedia.org/wiki/Young%27s_Literal_Translation",
				about: "Young's Literal Translation (YLT) is a translation of the Bible into English, published in 1862. The translation was made by Robert Young, compiler of Young's Analytical Concordance to the Bible and Concise Critical Comments on the New Testament. Young used the Textus Receptus (TR) and the Masoretic Text (MT) as the basis for his translation. He wrote in the preface to the first edition, \"It has been no part of the Translator's plan to attempt to form a New Hebrew or Greek Text—he has therefore somewhat rigidly adhered to the received ones.\"",
			},
		],
	});
	useEffect(() => {
		if (!init) {
			const defaultTheme =
				getBrowserStore("theme") !== null &&
				getBrowserStore("theme") !== ""
					? getBrowserStore("theme")
					: "default";
			toggleTheme(defaultTheme);

			const defaultUserData =
				getBrowserStore("userData") !== null &&
				getBrowserStore("userData") !== ""
					? JSON.parse(getBrowserStore("userData"))
					: userData;
			setUserData(defaultUserData);
			setInit(true);
		}
	}, [init, userData]);
	const selectBible = (value) => {
		let newUserData = { ...userData, bible: value };
		setUserData(newUserData);
		browserStore("userData", newUserData);
	};
	const selectCompare = (value) => {
		let newUserData = { ...userData, compare: value };
		setUserData(newUserData);
		browserStore("userData", newUserData);
	};
	const selectBook = (value) => {
		let newUserData = { ...userData, selected: { book: value, chapter: 1 } };
		setUserData(newUserData);
		browserStore("userData", newUserData);
	};
	const selectChapter = (value) => {
		let newUserData = { ...userData, selected: { book: userData.selected.book, chapter:  parseInt(value) } };
		setUserData(newUserData);
		browserStore("userData", newUserData);
	};
	const value = {
		userData,
		selectBible,
		selectCompare,
		appData,
		selectBook,
		selectChapter,
	};
	return (
		<AppDataContext.Provider value={value}>
			{props.children}
		</AppDataContext.Provider>
	);
}

export default AppDataContextProvifer;
